<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '9',
    'typeid' => '0',
    'title' => '测试数据1',
    'style' => '',
    'thumb' => '',
    'keywords' => '数据',
    'description' => '测试数据1',
    'posids' => '0',
    'url' => 'http://localhost/qax580/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'bingbing',
    'inputtime' => '1429550957',
    'updatetime' => '1429550969',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '9',
    'typeid' => '0',
    'title' => '测试数据2',
    'style' => '',
    'thumb' => '',
    'keywords' => '数据',
    'description' => '测试数据2',
    'posids' => '0',
    'url' => 'http://localhost/qax580/index.php?m=content&c=index&a=show&catid=9&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'bingbing',
    'inputtime' => '1429550970',
    'updatetime' => '1429550980',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>